# Generated by Django 4.2.11 on 2024-03-21 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('housing_median_age', models.FloatField()),
                ('total_rooms', models.FloatField()),
                ('total_bedrooms', models.FloatField()),
                ('population', models.FloatField()),
                ('households', models.FloatField()),
                ('median_income', models.FloatField()),
                ('ocean_proximity', models.CharField(max_length=100)),
                ('price_prediction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
